
metadb:
  host: 127.0.0.1
  port: 3306
  user: root
  password: **************1.
  base: chengken.starrocks_information_connections

server:
  port: 8084
  token: "123456"
  loadhtmlglob: templates/html/*
  loadstatic: templates/static


schema:
  role:
    admin: cndlopsns
    point: svc
  ipsystem: ops.cn_asset_information
  slowstmt: ops.ops_starrocks_schema_slowquery
  auditops: audit.starrocks_audit_log
  ipapp: sr-adhoc
  whitelist: root

category:
  0:
  1:
    - 'Connection reset by peer'
    - 'rpc failed'
    - 'since transaction status unknown'
    - 'Commit failed'
    - 'crash of backends'
    - 'Not connected to'
    - 'Fe abort the task'
    - 'no associated load channel'
    - 'Failed to lock database'
  2:
    - 'is not found'
    - 'cannot be resolved'
    - 'Unknown user'
    - 'Unknown table'
    - 'Access denied'
    - 'type:LOAD_RUN_FAIL; msg:Cancelled'
    - 'Mem usage has exceed the limit of single query'
    - 'please check trackingSQL'
    - 'is not active'

log:
  path: '/u/users/svccndlopsns/chengken/log'

