
metadb:
  host: 127.0.0.1
  port: 3306
  user: root
  password: **************1.
  base: chengken.starrocks_information_connections

server:
  port: 8084
  token: 123456
  loadhtmlglob: /u1/dlopsnas/chengken/templates/html/*
  loadstatic: /u1/dlopsnas/chengken/templates/static


schema:
  role:
    admin: cndlopsns
    point: svc
  ipsystem: ops.ops_starrocks_ip_system
  slowstmt: ops.ops_starrocks_schema_slowquery
  auditops: audit.starrocks_audit_log
  ipapp: sr-adhoc
  whitelist: root,cndlopsns,c0l0f9l,cndlsrapp,dorisops,svccn_flash_report,svccn_flash_report_dev,svccnodshs,svccnadssr_ec,svccndwdsr_ec,svccndimsr_ec,svccnsamshs,svccnfinsam,svccndwssr_ec,svccncdptodatalake,dding01,a0d0f8i,svccnfinhs_c,svccnfinsoxhs_c,svccnfinsoxhs_c_dev,svccnfinhs,svccnfinhs_c_dev,svccnfrhs_c,svccndatafinhs,svccnaudiths,svccncdpapp,svccncdptodatalake,svccnmaapp,svccncdpapi,svccn_ccop,svccncdpdata,ma_test_user

log:
  path: '/u/users/svccndlopsns/chengken/log'

